##
# @author Alexander Breuer (alex.breuer AT uni-jena.de)
#
# @section DESCRIPTION
# Collects sources for a build.
##
Import('env')

# gather sources
l_sources = [ 'solvers/Roe.cpp',
              'solvers/FWave.cpp',
              'patches/2d/WavePropagation2d.cpp',
              'simulator/Simulator.cpp',
              'setups/TsunamiEvent2d/TsunamiEvent2d.cpp',
              'setups/CheckPoint/CheckPoint.cpp',
              'configs/SimConfig.cpp',
              'io/Json/ConfigLoader.cpp',
              'io/NetCDF/NetCDF.cpp',
              'io/Csv/Csv.cpp',
              'MPIKernel/MPIKernel.cpp'
              ]

for l_so in l_sources:
  env.sources.append( env.Object( l_so ) )

env.standalone = env.Object( "main.cpp" )

# gather unit tests
l_tests = [ 'tests.cpp',
            'solvers/Roe.test.cpp',
            'solvers/FWave.test.cpp',
            'patches/2d/WavePropagation2d.test.cpp',
            'simulator/Simulator.test.cpp',
            'setups/TsunamiEvent2d/TsunamiEvent2d.test.cpp',
            'setups/CheckPoint/CheckPoint.test.cpp',
            'configs/SimConfig.test.cpp',
            'io/Json/ConfigLoader.test.cpp',
            'io/NetCDF/NetCDF.test.cpp',
            'io/Csv/Csv.test.cpp',
          ]

for l_te in l_tests:
  env.tests.append( env.Object( l_te ) )

Export('env')
